/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a normal install; it is checked in so
// static repository tests can validate TypeScript paths without running Node.
