"""Deterministic fixtures for TRIDENT Phase 3 hypothesis discovery."""

from __future__ import annotations

from typing import Any


def mr_fixture_data() -> dict[tuple[str, str], dict[str, Any]]:
    return {
        ("PCSK9", "LDL cholesterol"): {
            "exposure": "cis-pQTL/eQTL for PCSK9",
            "outcome": "LDL cholesterol GWAS",
            "coloc_h4": 0.93,
            "steiger_correct_direction": True,
            "instruments": [
                {
                    "variant": "rs11591147",
                    "beta_exposure": -0.32,
                    "beta_outcome": -0.18,
                    "se_outcome": 0.025,
                },
                {
                    "variant": "rs2479409",
                    "beta_exposure": 0.21,
                    "beta_outcome": 0.11,
                    "se_outcome": 0.020,
                },
                {
                    "variant": "rs11206510",
                    "beta_exposure": -0.17,
                    "beta_outcome": -0.09,
                    "se_outcome": 0.022,
                },
                {
                    "variant": "rs562556",
                    "beta_exposure": 0.14,
                    "beta_outcome": 0.08,
                    "se_outcome": 0.021,
                },
            ],
            "source_urls": [
                "https://www.nature.com/articles/ncomms4255",
                "https://www.ebi.ac.uk/gwas/",
            ],
        },
        ("height", "type 2 diabetes"): {
            "exposure": "height GWAS instruments",
            "outcome": "type 2 diabetes GWAS",
            "coloc_h4": 0.08,
            "steiger_correct_direction": False,
            "instruments": [
                {
                    "variant": "rsHEIGHT1",
                    "beta_exposure": 0.20,
                    "beta_outcome": 0.004,
                    "se_outcome": 0.035,
                },
                {
                    "variant": "rsHEIGHT2",
                    "beta_exposure": -0.18,
                    "beta_outcome": -0.002,
                    "se_outcome": 0.036,
                },
                {
                    "variant": "rsHEIGHT3",
                    "beta_exposure": 0.16,
                    "beta_outcome": -0.003,
                    "se_outcome": 0.034,
                },
                {
                    "variant": "rsHEIGHT4",
                    "beta_exposure": -0.14,
                    "beta_outcome": 0.002,
                    "se_outcome": 0.033,
                },
            ],
            "source_urls": [
                "https://www.ebi.ac.uk/gwas/",
                "https://pubmed.ncbi.nlm.nih.gov/30104761/",
            ],
        },
    }


def semmed_lbd_fixture_triples() -> list[dict[str, Any]]:
    return [
        {
            "subject": "fish oil",
            "predicate": "AFFECTS",
            "object": "blood viscosity",
            "pmid": "7201675",
            "year": 1981,
        },
        {
            "subject": "fish oil",
            "predicate": "AFFECTS",
            "object": "platelet aggregation",
            "pmid": "6123451",
            "year": 1982,
        },
        {
            "subject": "blood viscosity",
            "predicate": "AFFECTS",
            "object": "Raynaud disease",
            "pmid": "6338748",
            "year": 1984,
        },
        {
            "subject": "platelet aggregation",
            "predicate": "AFFECTS",
            "object": "Raynaud disease",
            "pmid": "6234567",
            "year": 1985,
        },
        {
            "subject": "fish oil",
            "predicate": "TREATS",
            "object": "Raynaud disease",
            "pmid": "3943917",
            "year": 1989,
        },
        {
            "subject": "magnesium",
            "predicate": "AFFECTS",
            "object": "spreading cortical depression",
            "pmid": "7012345",
            "year": 1982,
        },
        {
            "subject": "magnesium",
            "predicate": "AFFECTS",
            "object": "vascular tone",
            "pmid": "7012346",
            "year": 1984,
        },
        {
            "subject": "spreading cortical depression",
            "predicate": "CAUSES",
            "object": "migraine",
            "pmid": "7012347",
            "year": 1985,
        },
        {
            "subject": "vascular tone",
            "predicate": "AFFECTS",
            "object": "migraine",
            "pmid": "7012348",
            "year": 1986,
        },
        {
            "subject": "magnesium",
            "predicate": "PREVENTS",
            "object": "migraine",
            "pmid": "25533715",
            "year": 1992,
        },
        {
            "subject": "indomethacin",
            "predicate": "INHIBITS",
            "object": "prostaglandin synthesis",
            "pmid": "8012345",
            "year": 1978,
        },
        {
            "subject": "indomethacin",
            "predicate": "AFFECTS",
            "object": "neuroinflammation",
            "pmid": "8012346",
            "year": 1983,
        },
        {
            "subject": "prostaglandin synthesis",
            "predicate": "AFFECTS",
            "object": "Alzheimer disease",
            "pmid": "8012347",
            "year": 1985,
        },
        {
            "subject": "neuroinflammation",
            "predicate": "PREDISPOSES",
            "object": "Alzheimer disease",
            "pmid": "8012348",
            "year": 1985,
        },
        {
            "subject": "indomethacin",
            "predicate": "TREATS",
            "object": "Alzheimer disease",
            "pmid": "8019999",
            "year": 1990,
        },
    ]


def target_profiles() -> list[dict[str, Any]]:
    return [
        {
            "gene_symbol": "MUC5B",
            "uniprot_id": "Q9HC84",
            "disease_id": "MONDO:0008345",
            "disease_name": "idiopathic pulmonary fibrosis",
            "pharos_tdl": "Tbio",
            "publication_count": 620,
            "uzzi_z": -1.9,
            "llm_novelty_prior": 0.74,
            "pipeline_gap": 0.88,
            "druggability": {
                "tractability": "secreted mucin biology",
                "modalities": ["antisense", "biologic"],
                "has_structure": False,
                "pocketability": 0.55,
            },
            "evidence": {
                "mr_posterior": 0.74,
                "lbd_score": 0.70,
                "gwas_pip": 0.96,
                "expression_specificity": 0.84,
                "depmap_dependency": 0.15,
                "primekg_path_strength": 0.69,
                "patent_white_space": 0.82,
                "trial_failure_gap": 0.75,
                "contradictory_evidence": 0.05,
            },
        },
        {
            "gene_symbol": "AKAP13",
            "uniprot_id": "Q12802",
            "disease_id": "MONDO:0008345",
            "disease_name": "idiopathic pulmonary fibrosis",
            "pharos_tdl": "Tdark",
            "publication_count": 95,
            "uzzi_z": -2.4,
            "llm_novelty_prior": 0.83,
            "pipeline_gap": 0.93,
            "druggability": {
                "tractability": "scaffold signaling node",
                "modalities": ["PROTAC", "peptide"],
                "has_structure": True,
                "pocketability": 0.62,
            },
            "evidence": {
                "mr_posterior": 0.58,
                "lbd_score": 0.63,
                "gwas_pip": 0.72,
                "expression_specificity": 0.79,
                "depmap_dependency": 0.22,
                "primekg_path_strength": 0.64,
                "patent_white_space": 0.94,
                "trial_failure_gap": 0.86,
                "contradictory_evidence": 0.03,
            },
        },
        {
            "gene_symbol": "DPP9",
            "uniprot_id": "Q86TI2",
            "disease_id": "MONDO:0008345",
            "disease_name": "idiopathic pulmonary fibrosis",
            "pharos_tdl": "Tbio",
            "publication_count": 280,
            "uzzi_z": -1.6,
            "llm_novelty_prior": 0.68,
            "pipeline_gap": 0.81,
            "druggability": {
                "tractability": "enzyme active site",
                "modalities": ["small molecule"],
                "has_structure": True,
                "pocketability": 0.88,
            },
            "evidence": {
                "mr_posterior": 0.61,
                "lbd_score": 0.56,
                "gwas_pip": 0.85,
                "expression_specificity": 0.62,
                "depmap_dependency": 0.30,
                "primekg_path_strength": 0.58,
                "patent_white_space": 0.71,
                "trial_failure_gap": 0.70,
                "contradictory_evidence": 0.04,
            },
        },
        {
            "gene_symbol": "TERT",
            "uniprot_id": "O14746",
            "disease_id": "MONDO:0008345",
            "disease_name": "idiopathic pulmonary fibrosis",
            "pharos_tdl": "Tbio",
            "publication_count": 2_400,
            "uzzi_z": -0.7,
            "llm_novelty_prior": 0.51,
            "pipeline_gap": 0.76,
            "druggability": {
                "tractability": "enzyme/nucleoprotein",
                "modalities": ["small molecule", "oligonucleotide"],
                "has_structure": True,
                "pocketability": 0.70,
            },
            "evidence": {
                "mr_posterior": 0.69,
                "lbd_score": 0.44,
                "gwas_pip": 0.89,
                "expression_specificity": 0.58,
                "depmap_dependency": 0.18,
                "primekg_path_strength": 0.57,
                "patent_white_space": 0.60,
                "trial_failure_gap": 0.63,
                "contradictory_evidence": 0.08,
            },
        },
        {
            "gene_symbol": "EGFR",
            "uniprot_id": "P00533",
            "disease_id": "MONDO:0008345",
            "disease_name": "idiopathic pulmonary fibrosis",
            "pharos_tdl": "Tclin",
            "publication_count": 18_000,
            "uzzi_z": 0.2,
            "llm_novelty_prior": 0.18,
            "pipeline_gap": 0.52,
            "druggability": {
                "tractability": "kinase",
                "modalities": ["small molecule", "antibody"],
                "has_structure": True,
                "pocketability": 0.95,
            },
            "evidence": {
                "mr_posterior": 0.42,
                "lbd_score": 0.36,
                "gwas_pip": 0.40,
                "expression_specificity": 0.52,
                "depmap_dependency": 0.50,
                "primekg_path_strength": 0.48,
                "patent_white_space": 0.15,
                "trial_failure_gap": 0.25,
                "contradictory_evidence": 0.15,
            },
        },
        {
            "gene_symbol": "PARN",
            "uniprot_id": "O95453",
            "disease_id": "MONDO:0008345",
            "disease_name": "idiopathic pulmonary fibrosis",
            "pharos_tdl": "Tdark",
            "publication_count": 160,
            "uzzi_z": -2.1,
            "llm_novelty_prior": 0.76,
            "pipeline_gap": 0.91,
            "druggability": {
                "tractability": "ribonuclease",
                "modalities": ["small molecule", "RNA"],
                "has_structure": True,
                "pocketability": 0.66,
            },
            "evidence": {
                "mr_posterior": 0.52,
                "lbd_score": 0.49,
                "gwas_pip": 0.74,
                "expression_specificity": 0.67,
                "depmap_dependency": 0.21,
                "primekg_path_strength": 0.52,
                "patent_white_space": 0.90,
                "trial_failure_gap": 0.82,
                "contradictory_evidence": 0.04,
            },
        },
    ]
